package geometricSketchpad.gui;

import javax.swing.*;

import java.awt.*;
import java.awt.event.*;

import geometricSketchpad.tools.*;

/**
 * @(#)ToolboxPanel.java the toolbox panel for the gui, incomplete
 *
 *
 * @author Kaan Mert Berkem & Abdullah Çaðlar Öksüz
 * @version 1.00 2013/5/11
 */


/*public class ToolboxPanel extends JPanel //implements ActionListener 
{

    public ToolboxPanel() {
    	
    	//set the properties
    	setSize( new Dimension( 40, 200));
    	//TO DO
    	
    	//set the layout for buttons and add ActionListeners for each of them
    	setLayout( new GridLayout(10,2));
 		
 		for (int i = 0; i < 20; i++) {
 			JButton b;
 			b = new JButton();
 			b.setSize( 30,30);
// 			b.addActionListener(this);
 			add( b);
 			//TO DO
 		}
 		 		
 		//ActionPerformed method
// 		public void actionPerformed( ActionEvent e ) {
// 			System.out.println( "Incomplete!");
// 		}   	
    
    }
    
	public void paintComponent ( Graphics g) {
		super.paintComponent(g);
	}
    
}*/

public class ToolboxPanel extends javax.swing.JPanel implements ActionListener {

    /**
     * Creates new form ToolboxPanel
     */
	
	// properties                   
    private javax.swing.JButton circleButton;
    private javax.swing.JButton triangleButton;
    private javax.swing.JButton starButton;
    private javax.swing.JButton moveRotateButton;
    private javax.swing.JButton selectButton;
    private javax.swing.JButton ellipseButton;
    private javax.swing.JButton lineButton;
    private javax.swing.JButton lineSegmentButton;
    private javax.swing.JButton polygonButton;
    private javax.swing.JButton polyLineButton;
    private javax.swing.JButton rectangleButton;
    private javax.swing.JButton squareButton;
    private javax.swing.JButton equTriangleButton;  
    private javax.swing.JButton rulerButton;
	private javax.swing.JSeparator jSeparator1;
    
    // for testing purposes only
    public MainCanvas maincanvas;
    
    public ToolboxPanel(MainCanvas canvas) {
    	maincanvas = canvas;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        circleButton = new javax.swing.JButton();
        ellipseButton = new javax.swing.JButton();
        equTriangleButton = new javax.swing.JButton();
        lineSegmentButton = new javax.swing.JButton();
        polygonButton = new javax.swing.JButton();
        rectangleButton = new javax.swing.JButton();
        squareButton = new javax.swing.JButton();
        starButton = new javax.swing.JButton();
        triangleButton = new javax.swing.JButton();
        moveRotateButton = new javax.swing.JButton();
        selectButton = new javax.swing.JButton();
        polyLineButton = new javax.swing.JButton();
        lineButton = new javax.swing.JButton();
        rulerButton = new javax.swing.JButton();
		jSeparator1 = new javax.swing.JSeparator();
        
        circleButton.addActionListener( this );
        ellipseButton.addActionListener( this );
        lineButton.addActionListener( this );
        lineSegmentButton.addActionListener( this );
        polygonButton.addActionListener( this );
        polyLineButton.addActionListener( this );
        rectangleButton.addActionListener( this );
        squareButton.addActionListener( this );
        equTriangleButton.addActionListener( this );
        triangleButton.addActionListener( this );
        starButton.addActionListener( this );
        moveRotateButton.addActionListener( this );
        selectButton.addActionListener( this );
        rulerButton.addActionListener( this );

        setForeground(new java.awt.Color(255, 255, 255));

        circleButton.setIcon(new javax.swing.ImageIcon("geometricSketchpad\\images\\Circle.png")); // NOI18N
        circleButton.setToolTipText("Circle");
        circleButton.setMaximumSize(new java.awt.Dimension(50, 50));
        circleButton.setMinimumSize(new java.awt.Dimension(50, 50));
        circleButton.setPreferredSize(new java.awt.Dimension(50, 50));

        ellipseButton.setIcon(new javax.swing.ImageIcon("geometricSketchpad\\images\\Ellipse.png")); // NOI18N
        ellipseButton.setToolTipText("Ellipse");
        ellipseButton.setMaximumSize(new java.awt.Dimension(50, 50));
        ellipseButton.setMinimumSize(new java.awt.Dimension(50, 50));
        ellipseButton.setPreferredSize(new java.awt.Dimension(50, 50));

        equTriangleButton.setIcon(new javax.swing.ImageIcon("geometricSketchpad\\images\\Equilateral Triangle.png")); // NOI18N
        equTriangleButton.setToolTipText("Equilateral Triangle");
        equTriangleButton.setMaximumSize(new java.awt.Dimension(50, 50));
        equTriangleButton.setMinimumSize(new java.awt.Dimension(50, 50));
        equTriangleButton.setPreferredSize(new java.awt.Dimension(50, 50));

        lineSegmentButton.setIcon(new javax.swing.ImageIcon("geometricSketchpad\\images\\Line Segment.png")); // NOI18N
        lineSegmentButton.setToolTipText("Line Segment");
        lineSegmentButton.setMaximumSize(new java.awt.Dimension(50, 50));
        lineSegmentButton.setMinimumSize(new java.awt.Dimension(50, 50));
        lineSegmentButton.setPreferredSize(new java.awt.Dimension(50, 50));

        polygonButton.setIcon(new javax.swing.ImageIcon("geometricSketchpad\\images\\Polygon.png")); // NOI18N
        polygonButton.setToolTipText("Polygon");
        polygonButton.setMaximumSize(new java.awt.Dimension(50, 50));
        polygonButton.setMinimumSize(new java.awt.Dimension(50, 50));
        polygonButton.setPreferredSize(new java.awt.Dimension(50, 50));

        rectangleButton.setIcon(new javax.swing.ImageIcon("geometricSketchpad\\images\\Rectangle.png")); // NOI18N
        rectangleButton.setToolTipText("Rectangle");
        rectangleButton.setMaximumSize(new java.awt.Dimension(50, 50));
        rectangleButton.setMinimumSize(new java.awt.Dimension(50, 50));
        rectangleButton.setPreferredSize(new java.awt.Dimension(50, 50));

        squareButton.setIcon(new javax.swing.ImageIcon("geometricSketchpad\\images\\Square.png")); // NOI18N
        squareButton.setToolTipText("Square");
        squareButton.setMaximumSize(new java.awt.Dimension(50, 50));
        squareButton.setMinimumSize(new java.awt.Dimension(50, 50));
        squareButton.setPreferredSize(new java.awt.Dimension(50, 50));

        starButton.setIcon(new javax.swing.ImageIcon("geometricSketchpad\\images\\Star.png")); // NOI18N
        starButton.setToolTipText("Star");
        starButton.setMaximumSize(new java.awt.Dimension(50, 50));
        starButton.setMinimumSize(new java.awt.Dimension(50, 50));
        starButton.setPreferredSize(new java.awt.Dimension(50, 50));

        triangleButton.setIcon(new javax.swing.ImageIcon("geometricSketchpad\\images\\Triangle.png")); // NOI18N
        triangleButton.setToolTipText("Triangle");
        triangleButton.setMaximumSize(new java.awt.Dimension(50, 50));
        triangleButton.setMinimumSize(new java.awt.Dimension(50, 50));
        triangleButton.setPreferredSize(new java.awt.Dimension(50, 50));

        moveRotateButton.setIcon(new javax.swing.ImageIcon("geometricSketchpad\\images\\Rotate.png")); // NOI18N
        moveRotateButton.setToolTipText("Move / Rotate");
        moveRotateButton.setMaximumSize(new java.awt.Dimension(50, 50));
        moveRotateButton.setMinimumSize(new java.awt.Dimension(50, 50));
        moveRotateButton.setPreferredSize(new java.awt.Dimension(50, 50));

        selectButton.setIcon(new javax.swing.ImageIcon("geometricSketchpad\\images\\Select.png")); // NOI18N
        selectButton.setToolTipText("Select");
        selectButton.setMaximumSize(new java.awt.Dimension(50, 50));
        selectButton.setMinimumSize(new java.awt.Dimension(50, 50));
        selectButton.setPreferredSize(new java.awt.Dimension(50, 50));

        polyLineButton.setIcon(new javax.swing.ImageIcon("geometricSketchpad\\images\\Polyline.png")); // NOI18N
        polyLineButton.setToolTipText("Polyline");
        polyLineButton.setMaximumSize(new java.awt.Dimension(50, 50));
        polyLineButton.setMinimumSize(new java.awt.Dimension(50, 50));
        polyLineButton.setPreferredSize(new java.awt.Dimension(50, 50));

        lineButton.setIcon(new javax.swing.ImageIcon("geometricSketchpad\\images\\Line.png")); // NOI18N
        lineButton.setToolTipText("Line");
        lineButton.setMaximumSize(new java.awt.Dimension(50, 50));
        lineButton.setMinimumSize(new java.awt.Dimension(50, 50));
        lineButton.setPreferredSize(new java.awt.Dimension(50, 50));
        
        rulerButton.setIcon(new javax.swing.ImageIcon("geometricSketchpad\\images\\Ruler.png")); // NOI18N
        rulerButton.setToolTipText("Ruler");
        rulerButton.setMaximumSize(new java.awt.Dimension(50, 50));
        rulerButton.setMinimumSize(new java.awt.Dimension(50, 50));
        rulerButton.setPreferredSize(new java.awt.Dimension(50, 50));
		
		jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(circleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ellipseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lineSegmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(polygonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(polyLineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rectangleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(squareButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(equTriangleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(triangleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(starButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rulerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moveRotateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    /*addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(equTriangleButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(starButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rectangleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(triangleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rulerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(moveRotateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(squareButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))*/
               // .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 110, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)))
        )));
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ellipseButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(circleButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lineSegmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lineButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(polyLineButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(polygonButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rectangleButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(squareButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(equTriangleButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(triangleButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(starButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rulerButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(selectButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(moveRotateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE))
        );
    }                       

    
    
    public void actionPerformed ( ActionEvent e) {
        if( (JButton) e.getSource() == circleButton )
            maincanvas.setActiveTool( new CircleTool());
        else if( (JButton) e.getSource() == ellipseButton )
            maincanvas.setActiveTool( new EllipseTool());
        else if( (JButton) e.getSource() == lineButton )
            maincanvas.setActiveTool( new LineTool());
        else if( (JButton) e.getSource() == lineSegmentButton )
            maincanvas.setActiveTool( new LineSegmentTool());
        else if( (JButton) e.getSource() == polygonButton )
            maincanvas.setActiveTool( new PolygonTool());
        else if( (JButton) e.getSource() == polyLineButton )
            maincanvas.setActiveTool( new PolyLineTool());
        else if( (JButton) e.getSource() == rectangleButton )
            maincanvas.setActiveTool( new RectangleTool());
        else if( (JButton) e.getSource() == squareButton )
            maincanvas.setActiveTool( new SquareTool());
        else if( (JButton) e.getSource() == equTriangleButton )
            maincanvas.setActiveTool( new EquilateralTriangleTool());
        else if( (JButton) e.getSource() == triangleButton )
            maincanvas.setActiveTool( new TriangleTool());
        else if( (JButton) e.getSource() == starButton )
            maincanvas.setActiveTool( new NStarTool(5));
        else if( (JButton) e.getSource() == moveRotateButton )
            maincanvas.setActiveTool( new MoveRotateTool( maincanvas.getShapes() ) );
        else if( (JButton) e.getSource() == selectButton )
            maincanvas.setActiveTool( new SelectTool( maincanvas.getShapes() ) );
        else if( (JButton) e.getSource() == rulerButton )
            maincanvas.setActiveTool( new RulerTool() );
    }
    
    public static void main( String[] args )
    {
    	//MainCanvas mcan = new MainCanvas();
    	ToolboxPanel t = new ToolboxPanel(new MainCanvas());
    //	t.maincanvas = ;
		JFrame frame = new JFrame("MAIN CANVAS");
		frame.setLayout(new BorderLayout());
	//	frame.add(t.maincanvas, BorderLayout.CENTER);
		frame.add(t, BorderLayout.WEST );
		frame.pack();
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.setVisible(true);
    }
}